"""
Diet plan SQLAlchemy model.
Stores generated meal plans and macro allocations.
"""

from __future__ import annotations

from datetime import datetime, timezone
from sqlalchemy import Boolean, Column, DateTime, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import relationship

from app.core.database import Base


def _utcnow() -> datetime:
    return datetime.now(timezone.utc).replace(tzinfo=None)


class DietPlan(Base):
    """User diet plan generated by the AI Fitness Coach."""

    __tablename__ = "diet_plans"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    user_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    title = Column(String(255), nullable=False)
    fitness_goal = Column(String(50), nullable=False)  # weight_loss, muscle_gain, maintenance, etc.
    dietary_preference = Column(String(50), nullable=False)  # omnivore, vegetarian, vegan, keto, etc.
    target_calories = Column(Float, nullable=False)
    target_protein_g = Column(Float, nullable=False)
    target_carbs_g = Column(Float, nullable=False)
    target_fats_g = Column(Float, nullable=False)
    meals = Column(Text, nullable=False)  # JSON-encoded list of meal dicts
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=_utcnow, nullable=False, index=True)

    # Relationships
    user = relationship("User", back_populates="diet_plans")

    def __repr__(self) -> str:
        return (
            f"<DietPlan(id={self.id}, user_id={self.user_id}, "
            f"title={self.title!r}, calories={self.target_calories})>"
        )
