"""
Exercise form analysis SQLAlchemy model.
Stores video / camera form feedback generated by the Gemini Video Analyzer.
"""

from __future__ import annotations

from datetime import datetime, timezone
from sqlalchemy import Column, DateTime, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import relationship

from app.core.database import Base


def _utcnow() -> datetime:
    return datetime.now(timezone.utc).replace(tzinfo=None)


class FormAnalysisRecord(Base):
    """Stores video-based or frame-based exercise form analysis results."""

    __tablename__ = "form_analyses"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    user_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    exercise_name = Column(String(100), nullable=False)
    video_filename = Column(String(255), nullable=True)
    form_score = Column(Float, nullable=False)  # 0 to 100
    rep_count = Column(Integer, nullable=False, default=0)
    posture_summary = Column(String(255), nullable=False)
    detailed_feedback = Column(Text, nullable=False)  # JSON or detailed evaluation text
    injury_risk_level = Column(String(50), nullable=False)  # low, medium, high
    recommendations = Column(Text, nullable=False)
    created_at = Column(DateTime, default=_utcnow, nullable=False, index=True)

    # Relationships
    user = relationship("User", back_populates="form_analyses")

    @property
    def keypoint_checks(self) -> str:
        """Alias property matching FormAnalysisResponse schema."""
        return self.detailed_feedback

    def __repr__(self) -> str:
        return (
            f"<FormAnalysisRecord(id={self.id}, user_id={self.user_id}, "
            f"exercise={self.exercise_name!r}, score={self.form_score})>"
        )
