"""
Workout plan SQLAlchemy model.
Stores generated training routines and schedules.
"""

from __future__ import annotations

from datetime import datetime, timezone
from sqlalchemy import Boolean, Column, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import relationship

from app.core.database import Base


def _utcnow() -> datetime:
    return datetime.now(timezone.utc).replace(tzinfo=None)


class WorkoutPlan(Base):
    """User workout plan generated by the AI Fitness Coach."""

    __tablename__ = "workout_plans"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    user_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    title = Column(String(255), nullable=False)
    fitness_level = Column(String(50), nullable=False)  # beginner, intermediate, advanced
    fitness_goal = Column(String(50), nullable=False)   # strength, hypertrophy, fat_loss, endurance
    days_per_week = Column(Integer, nullable=False)
    equipment = Column(String(100), nullable=False)     # full_gym, dumbbells, bodyweight_only
    routines = Column(Text, nullable=False)             # JSON-encoded list of routine dicts
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=_utcnow, nullable=False, index=True)

    # Relationships
    user = relationship("User", back_populates="workout_plans")

    def __repr__(self) -> str:
        return (
            f"<WorkoutPlan(id={self.id}, user_id={self.user_id}, "
            f"title={self.title!r}, days={self.days_per_week})>"
        )
